version: "3.9"

services:
  airflow_webserver:
    image: apache/airflow:2.6.3-python3.9
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spcapetmatchmaker:spcapetmatchmaker@postgres:5432/spcapetmatchmaker
      - AIRFLOW__CORE__EXECUTOR=airflow.executors.local_executor.LocalExecutor
      - AIRFLOW__SCHEDULER__CATCHUP=False
      - AIRFLOW__WEBSERVER__WEB_SERVER_URL=http://127.0.0.1:8080
      - AIRFLOW__WEBSERVER__SECRET_KEY=SomeStrongSecretKey
      - AIRFLOW__CORE__SECRET_KEY=SomeStrongSecretKey
    depends_on:
      - postgres
      - airflow_db_init
      - airflow_user_init
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "pip install docker && airflow webserver"
    healthcheck:
      test: ["CMD-SHELL", "airflow webserver status"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow_scheduler:
    image: apache/airflow:2.6.3-python3.9
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spcapetmatchmaker:spcapetmatchmaker@postgres:5432/spcapetmatchmaker
      - AIRFLOW__CORE__EXECUTOR=airflow.executors.local_executor.LocalExecutor
      - AIRFLOW__SCHEDULER__CATCHUP=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=SomeStrongSecretKey
      - AIRFLOW__CORE__SECRET_KEY=SomeStrongSecretKey
    depends_on:
      - postgres
      - airflow_db_init
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "pip install docker && airflow scheduler"

  airflow_db_init:
    image: apache/airflow:2.6.3-python3.9
    container_name: airflow_db_init
    command: ["airflow", "db", "init"]
    restart: on-failure
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spcapetmatchmaker:spcapetmatchmaker@postgres:5432/spcapetmatchmaker
      - AIRFLOW__CORE__EXECUTOR=airflow.executors.local_executor.LocalExecutor
      - AIRFLOW__SCHEDULER__CATCHUP=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=SomeStrongSecretKey
      - AIRFLOW__CORE__SECRET_KEY=SomeStrongSecretKey
    depends_on:
      - postgres

  airflow_user_init:
    image: apache/airflow:2.6.3-python3.9
    container_name: airflow_user_init
    command: [
      "airflow", "users", "create", 
      "--role", "Admin", 
      "--username", "airflow", 
      "--password", "airflow",
      "--email", "airflow@airflow.com",
      "--firstname", "airflow",
      "--lastname", "airflow"
    ]
    restart: on-failure
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://spcapetmatchmaker:spcapetmatchmaker@postgres:5432/spcapetmatchmaker
      - AIRFLOW__CORE__EXECUTOR=airflow.executors.local_executor.LocalExecutor
      - AIRFLOW__SCHEDULER__CATCHUP=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=SomeStrongSecretKey
      - AIRFLOW__CORE__SECRET_KEY=SomeStrongSecretKey
    depends_on:
      - postgres
      - airflow_db_init