version: "3.9"

services:
  webapp:
    image: spca_webapp:latest
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_DSN=postgresql+psycopg2://spcapetmatchmaker:spcapetmatchmaker@postgres:5432/spcapetmatchmaker
    depends_on:
      - postgres
      - migrations