version: "3.9"

services:
  directus:
    image: directus/directus:11.5.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      - postgres
    environment:
      SECRET: "replace-with-secure-random-value"
      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "spcapetmatchmaker"
      DB_USER: "spcapetmatchmaker"
      DB_PASSWORD: "spcapetmatchmaker"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"