version: "3.9"

services:
  postgres:
    image: postgres:13  # Or your preferred Postgres version
    environment:
      - POSTGRES_USER=spcapetmatchmaker
      - POSTGRES_PASSWORD=spcapetmatchmaker
      - POSTGRES_DB=spcapetmatchmaker
    ports:
      - "5432:5432" # Expose Postgres port if needed for external tools, but not strictly required for Airflow
    volumes: # Persist the database data (optional, but recommended)
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Add a healthcheck for Postgres readiness
      test: ["CMD-SHELL", "pg_isready -U spcapetmatchmaker -d spcapetmatchmaker"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: flyway/flyway:9.22.3  # Use the latest Flyway version
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./database/migrations:/flyway/sql  # Mount the local migrations folder
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/spcapetmatchmaker
      - FLYWAY_USER=spcapetmatchmaker
      - FLYWAY_PASSWORD=spcapetmatchmaker
      - FLYWAY_BASELINE_ON_MIGRATE=true
    command: migrate  # Run the migrate command on startup

volumes:
  postgres_data: # Named volume for Postgres data