version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg13
    environment:
      - POSTGRES_USER=spcapetmatchmaker
      - POSTGRES_PASSWORD=spcapetmatchmaker
      - POSTGRES_DB=spcapetmatchmaker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spcapetmatchmaker -d spcapetmatchmaker"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: flyway/flyway:9.22.3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./database/migrations:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/spcapetmatchmaker
      - FLYWAY_USER=spcapetmatchmaker
      - FLYWAY_PASSWORD=spcapetmatchmaker
      - FLYWAY_BASELINE_ON_MIGRATE=true
    command: migrate

volumes:
  postgres_data: