CREATE TABLE IF NOT EXISTS profile (
    account_id INT NOT NULL,
    affectionate_with_family INT DEFAULT 1,
    good_with_young_children INT DEFAULT 1,
    good_with_other_dogs INT DEFAULT 1,
    shedding_level INT DEFAULT 1,
    coat_grooming_frequency INT DEFAULT 1,
    drooling_level INT DEFAULT 1,
    coat_length INT DEFAULT 1,
    openness_to_strangers INT DEFAULT 1,
    playfulness_level INT DEFAULT 1,
    watchdog_protective_nature INT DEFAULT 1,
    adaptability_level INT DEFAULT 1,
    trainability_level INT DEFAULT 1,
    energy_level INT DEFAULT 1,
    barking_level INT DEFAULT 1,
    mental_stimulation_needs INT DEFAULT 1,
    latitude DECIMAL(11, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    nearest_spca VARCHAR(50) NOT NULL,
    FOREIGN KEY (nearest_spca) REFERENCES spca(id),
    FOREIGN KEY (account_id) REFERENCES account(id)
);